# Generated by Django 4.1.6 on 2023-03-09 06:33

import ReFinance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinance', '0002_currency_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='expiration_date',
            field=models.DateTimeField(default=ReFinance.models.set_expire),
        ),
    ]
